package aptdat

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"airspace-acars/internal/domain"
)

// Rows as X-Plane writes them. Heathrow's northern runway, two of its
// stands, and the metadata that names it.
const egllRows = `1    83 0 0 EGLL London Heathrow
1302 icao_code EGLL
1302 datum_lat 51.477500
1302 datum_lon -0.461389
100 50.00 1 0 0.25 1 3 0 09L  51.47750000 -000.48496100  307.00 0.00 3 12 1 0 27R  51.47766100 -000.43312800    0.00 0.00 3 12 1 0
110 1 0.25 90.00 Apron
111 51.47100000 -000.45000000
1300 51.47120000 -000.45980000 271.00 gate jets|turboprops A12
1300 51.47130000 -000.45900000 271.00 gate jets Remote Stand 5
1300 not-a-number -000.45900000 271.00 gate jets Broken
`

// A small field a few kilometres away, to make sure the right one is chosen.
const egwuRows = `1   120 0 0 EGWU Northolt
100 46.00 1 0 0.25 0 2 0 07 51.54900000 -000.43200000 0.00 0.00 2 0 0 0 25 51.55600000 -000.39800000 0.00 0.00 2 0 0 0
`

const globalAptDat = "I\n1200 Generated by WorldEditor\n\n" + egllRows + "\n" + egwuRows + "\n99\n"

// The same airport in a custom scenery pack, with stands named its own way.
const customEGLL = "I\n1100 Custom\n\n" + `1    83 0 0 EGLL London Heathrow (payware)
100 50.00 1 0 0.25 1 3 0 09L  51.47750000 -000.48496100  307.00 0.00 3 12 1 0 27R  51.47766100 -000.43312800    0.00 0.00 3 12 1 0
1300 51.47120000 -000.45980000 271.00 gate jets 412
99
`

const egllCIFP = `APPCH:010,A,I09L,ILL,CI09L,EG,P,C,E  M, ,   ,CF, ,ILL,EG,P,I,      ,0897,0091,0900,0060,+,02500,     ,     , ,   ,    ,   , , , , , ,0,D,S;
RWY:RW09L,      ,      ,00079,   ,ILL  ,3,   ;N51284660,W000291154,0000;
RWY:RW27R,      ,      ,00078,   ,IRR  ,3,   ;N51283810,W000260010,1001;
RWY:garbage
`

// xplaneRoot builds an X-Plane folder holding the given files.
func xplaneRoot(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

const globalPath = "Global Scenery/Global Airports/Earth nav data/apt.dat"

func sourceAt(root string) *Source {
	s := NewSource(func() string { return root })
	s.findRunning = func() (string, bool) { return "", false }
	return s
}

// atStandA12 is an aircraft parked on Heathrow's stand A12.
const atA12Lat, atA12Lon = 51.47121, -0.45981

// The whole path: the index is built from the global airports, the airport
// the aircraft is at is read back, and its runway ends get their own
// elevations from the navdata.
func TestAnAirportIsReadFromTheGlobalAirports(t *testing.T) {
	root := xplaneRoot(t, map[string]string{
		globalPath:                             globalAptDat,
		"Resources/default data/CIFP/EGLL.dat": egllCIFP,
	})
	l, err := sourceAt(root).NearestAirportLayout(context.Background(), atA12Lat, atA12Lon)
	if err != nil {
		t.Fatal(err)
	}
	if l.ICAO != "EGLL" || len(l.Runways) != 1 {
		t.Fatalf("layout = %+v, want EGLL with one runway", l)
	}
	ends := l.Runways[0].Ends
	if ends[0].Designator != "09L" || ends[0].Lat != 51.4775 || ends[0].Lon != -0.484961 || ends[1].Designator != "27R" {
		t.Fatalf("runway ends = %+v", ends)
	}
	if ends[0].AltFt != 79 || ends[1].AltFt != 78 {
		t.Fatalf("end elevations = %.0f, %.0f ft; the CIFP gives 79 and 78", ends[0].AltFt, ends[1].AltFt)
	}
	names := []string{}
	for _, s := range l.Stands {
		names = append(names, s.Name)
	}
	if strings.Join(names, ",") != "A12,Remote Stand 5" {
		t.Fatalf("stands = %v, want A12 and Remote Stand 5 (the broken row skipped)", names)
	}
	if l.RefLat != 51.4775 || l.RefLon != -0.461389 {
		t.Fatalf("reference = %v,%v, want the datum", l.RefLat, l.RefLon)
	}
}

// The pilot's AIRAC cycle in Custom Data wins over the navdata X-Plane
// ships; without either, the ends keep the airport elevation.
func TestRunwayElevationsComeFromTheNewestNavdata(t *testing.T) {
	airac := strings.ReplaceAll(egllCIFP, "00079", "00081")
	root := xplaneRoot(t, map[string]string{
		globalPath:                             globalAptDat,
		"Custom Data/CIFP/EGLL.dat":            airac,
		"Resources/default data/CIFP/EGLL.dat": egllCIFP,
	})
	l, err := sourceAt(root).NearestAirportLayout(context.Background(), atA12Lat, atA12Lon)
	if err != nil {
		t.Fatal(err)
	}
	if got := l.Runways[0].Ends[0].AltFt; got != 81 {
		t.Fatalf("09L elevation = %.0f ft, want the AIRAC's 81", got)
	}

	bare := xplaneRoot(t, map[string]string{globalPath: globalAptDat})
	l, err = sourceAt(bare).NearestAirportLayout(context.Background(), atA12Lat, atA12Lon)
	if err != nil {
		t.Fatal(err)
	}
	if got := l.Runways[0].Ends[0].AltFt; got != 83 {
		t.Fatalf("09L elevation without navdata = %.0f ft, want the airport's 83", got)
	}
}

// A custom scenery pack replaces the global version of its airport, as it
// does in the simulator.
func TestCustomSceneryWinsOverTheGlobalAirports(t *testing.T) {
	root := xplaneRoot(t, map[string]string{
		globalPath: globalAptDat,
		"Custom Scenery/Payware EGLL/Earth nav data/apt.dat": customEGLL,
		"Custom Scenery/scenery_packs.ini": "I\n1000 Version\nSCENERY\n\n" +
			"SCENERY_PACK Custom Scenery/Payware EGLL/\n" +
			"SCENERY_PACK *GLOBAL_AIRPORTS*\n",
	})
	l, err := sourceAt(root).NearestAirportLayout(context.Background(), atA12Lat, atA12Lon)
	if err != nil {
		t.Fatal(err)
	}
	if len(l.Stands) != 1 || l.Stands[0].Name != "412" {
		t.Fatalf("stands = %+v, want the payware's stand 412", l.Stands)
	}
}

func TestSceneryPacksAreReadInTheSimulatorsOrder(t *testing.T) {
	pack := func(name string) string { return "Custom Scenery/" + name + "/Earth nav data/apt.dat" }
	root := xplaneRoot(t, map[string]string{
		globalPath:        "I\n99\n",
		pack("First"):     "I\n99\n",
		pack("Disabled"):  "I\n99\n",
		pack("Last"):      "I\n99\n",
		pack("NotListed"): "I\n99\n",
		"Custom Scenery/scenery_packs.ini": "I\n1000 Version\nSCENERY\n\n" +
			"SCENERY_PACK Custom Scenery/First/\n" +
			"SCENERY_PACK_DISABLED Custom Scenery/Disabled/\n" +
			"SCENERY_PACK *GLOBAL_AIRPORTS*\n" +
			"SCENERY_PACK Custom Scenery/Last/\r\n" +
			"SCENERY_PACK Custom Scenery/Missing/\n",
	})
	var got []string
	for _, f := range sceneryFiles(root) {
		rel, _ := filepath.Rel(root, f)
		got = append(got, filepath.ToSlash(rel))
	}
	want := []string{pack("First"), globalPath, pack("Last")}
	if strings.Join(got, "|") != strings.Join(want, "|") {
		t.Fatalf("apt.dat order = %v\nwant %v", got, want)
	}

	// X-Plane 11 has no *GLOBAL_AIRPORTS* line: the global airports come last.
	xp11 := xplaneRoot(t, map[string]string{
		"Resources/default scenery/default apt dat/Earth nav data/apt.dat": "I\n99\n",
		pack("Mine"):                       "I\n99\n",
		"Custom Scenery/scenery_packs.ini": "SCENERY_PACK Custom Scenery/Mine/\n",
	})
	files := sceneryFiles(xp11)
	if len(files) != 2 || !strings.Contains(filepath.ToSlash(files[1]), "default apt dat") {
		t.Fatalf("X-Plane 11 order = %v, want the pack then the default airports", files)
	}
}

// The airport chosen is the one the aircraft is on, and none at sea.
func TestTheAirportUnderTheAircraftIsChosen(t *testing.T) {
	root := xplaneRoot(t, map[string]string{globalPath: globalAptDat})
	s := sourceAt(root)

	l, err := s.NearestAirportLayout(context.Background(), 51.552, -0.415)
	if err != nil || l.ICAO != "EGWU" {
		t.Fatalf("on Northolt's runway got %+v, %v", l, err)
	}
	if _, err := s.NearestAirportLayout(context.Background(), 50.0, -20.0); !errors.Is(err, domain.ErrNoAirportData) {
		t.Fatalf("mid-Atlantic: err = %v, want ErrNoAirportData", err)
	}
}

// Without an X-Plane folder there is nothing to read, which is not a fault.
func TestNoXPlaneFolderIsNoAirportData(t *testing.T) {
	s := sourceAt("")
	if _, err := s.NearestAirportLayout(context.Background(), atA12Lat, atA12Lon); !errors.Is(err, domain.ErrNoAirportData) {
		t.Fatalf("err = %v, want ErrNoAirportData", err)
	}
	empty := sourceAt(t.TempDir())
	if _, err := empty.NearestAirportLayout(context.Background(), atA12Lat, atA12Lon); !errors.Is(err, domain.ErrNoAirportData) {
		t.Fatalf("folder without apt.dat: err = %v, want ErrNoAirportData", err)
	}
}

// The running simulator is used when no folder is set.
func TestTheRunningXPlaneIsFoundWhenNoFolderIsSet(t *testing.T) {
	root := xplaneRoot(t, map[string]string{globalPath: globalAptDat})
	s := NewSource(func() string { return "  " })
	s.findRunning = func() (string, bool) { return root, true }
	if _, err := s.NearestAirportLayout(context.Background(), atA12Lat, atA12Lon); err != nil {
		t.Fatal(err)
	}
}

// A malformed airport keeps what can be read; rows from the next airport
// never leak into it.
func TestAnAirportIsReadUpToTheNextOne(t *testing.T) {
	rec, err := parseAirport(strings.NewReader(egllRows + "100 short row\n" + egwuRows))
	if err != nil {
		t.Fatal(err)
	}
	if rec.ident != "EGLL" || rec.icao != "EGLL" || len(rec.runways) != 1 || len(rec.stands) != 2 {
		t.Fatalf("record = %+v", rec)
	}
	if _, err := parseAirport(strings.NewReader("99\n")); !errors.Is(err, errNotAnAirport) {
		t.Fatalf("end-of-file row read as an airport: %v", err)
	}
}

func TestCIFPRunwayRecordsAreRead(t *testing.T) {
	got := parseCIFPElevations(strings.NewReader(egllCIFP + "RWY:RW18,  ,  ,-0012,\nRWY:RWX,1,2,abc,\n"))
	want := map[string]float64{"09L": 79, "27R": 78, "18": -12}
	if len(got) != len(want) {
		t.Fatalf("elevations = %v, want %v", got, want)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %v, want %v", k, got[k], v)
		}
	}
}

// The ident becomes a file name, so it must be one and nothing more.
func TestOnlyAirportIdentsNameCIFPFiles(t *testing.T) {
	for _, bad := range []string{"", "../EGLL", `..\x`, "EG LL", "egll", "TOOLONGID"} {
		if validIdent(bad) {
			t.Errorf("%q accepted as an airport ident", bad)
		}
	}
	for _, ok := range []string{"EGLL", "KJFK", "X1", "SBGR"} {
		if !validIdent(ok) {
			t.Errorf("%q rejected as an airport ident", ok)
		}
	}
}
