import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test-setup.ts"],
  },
  resolve: {
    alias: [
      { find: "@", replacement: path.resolve(__dirname, "./src") },
      { find: "@wailsio/runtime", replacement: path.resolve(__dirname, "./src/__mocks__/wails-runtime.ts") },
      // Generated by `wails3 generate bindings` and gitignored — see the mock file for why
      // this is aliased. Both relative depths in use: src/{context,hooks,components}/*
      // import "../../bindings/...", src/main.tsx imports "../bindings/...".
      { find: "../../bindings/airspace-acars", replacement: path.resolve(__dirname, "./src/__mocks__/wails-bindings-module.ts") },
      { find: "../bindings/airspace-acars", replacement: path.resolve(__dirname, "./src/__mocks__/wails-bindings-module.ts") },
    ],
  },
});
