package app

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"
)

type documentAPI struct {
	stubAPI
	path string
}

func (*documentAPI) Token() string { return "pilot-token" }
func (s *documentAPI) DoRequest(method, path string, body interface{}) ([]byte, int, error) {
	s.path = path
	return s.stubAPI.DoRequest(method, path, body)
}

func TestDocumentListPaginationAndQuery(t *testing.T) {
	api := &documentAPI{stubAPI: stubAPI{
		status: 200,
		body:   []byte(`{"data":[{"id":101,"title":"B737 SOP","type":"html","content":"<p>Standard Operating Procedures</p>","is_auto_generated":0,"parent_id":null}],"meta":{"current_page":1,"last_page":2}}`),
	}}
	a := &App{Airspace: api}
	result, err := a.GetDocuments(1, "folder_5", "SOP")
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "ok" || len(result.Data) != 1 || result.Data[0].ID != "101" || result.Data[0].Title != "B737 SOP" {
		t.Fatalf("unexpected response: %+v", result)
	}
	u, _ := url.Parse(api.path)
	q := u.Query()
	if u.Path != "/api/v2/acars/documents" || q.Get("filter[parent_id]") != "folder_5" || q.Get("filter[title]") != "SOP" {
		t.Fatalf("wrong request: %s", api.path)
	}
}

func TestDocumentUnavailableStatuses(t *testing.T) {
	for status, want := range map[int]string{401: "accessDenied", 403: "accessDenied", 404: "unavailable", 405: "unavailable", 429: "rateLimited"} {
		api := &documentAPI{stubAPI: stubAPI{status: status, body: []byte("error")}}
		a := &App{Airspace: api}
		result, err := a.GetDocuments(1, "", "")
		if err != nil || result.Status != want {
			t.Fatalf("status %d: got status %q, want %q (err: %v)", status, result.Status, want, err)
		}
	}
}

func TestDocumentLocalModeAndNoSession(t *testing.T) {
	api := &documentAPI{}
	a := &App{Airspace: api}
	a.settings.LocalMode = true
	result, err := a.GetDocuments(1, "", "")
	if err != nil || result.Status != "localMode" || api.calls != 0 {
		t.Fatalf("unexpected local request: %+v %v", result, err)
	}

	noSession := &stubAPI{}
	a = &App{Airspace: noSession}
	result, err = a.GetDocuments(1, "", "")
	if err != nil || result.Status != "noSession" || noSession.calls != 0 {
		t.Fatalf("unexpected anonymous request: %+v %v", result, err)
	}
}

func TestDocumentDetailAndSecurity(t *testing.T) {
	api := &documentAPI{stubAPI: stubAPI{status: 200}}
	a := &App{Airspace: api}
	api.body = []byte(`{"data":{"id":"202","title":"Airport Briefing SBGR","type":"auto_generated","content":"<p>Obstacles and terrain caution</p>","is_auto_generated":1}}`)
	detail, err := a.GetDocument("202")
	if err != nil || detail.Data == nil || detail.Data.ID != "202" || !detail.Data.IsAutoGenerated {
		t.Fatalf("unexpected detail: %+v %v", detail, err)
	}

	for _, unsafeID := range []string{"", "../etc/passwd", "https://evil.com", "folder/file", "%2e%2e"} {
		if _, err := a.GetDocument(unsafeID); err == nil {
			t.Fatalf("accepted unsafe document id: %q", unsafeID)
		}
	}
}

func TestValidateDocumentURL(t *testing.T) {
	tests := []struct {
		name    string
		rawURL  string
		baseURL string
		wantURL string
		wantErr bool
	}{
		{
			name:    "valid https URL",
			rawURL:  "https://airspace.ferrlab.com/docs/sop.pdf",
			baseURL: "https://airspace.ferrlab.com",
			wantURL: "https://airspace.ferrlab.com/docs/sop.pdf",
		},
		{
			name:    "valid http URL",
			rawURL:  "http://example.com/briefing.html",
			baseURL: "https://airspace.ferrlab.com",
			wantURL: "http://example.com/briefing.html",
		},
		{
			name:    "valid relative URL resolved against base URL",
			rawURL:  "/storage/documents/manual.pdf",
			baseURL: "https://airline.example.com",
			wantURL: "https://airline.example.com/storage/documents/manual.pdf",
		},
		{
			name:    "empty URL returns error",
			rawURL:  "",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "whitespace only returns error",
			rawURL:  "   ",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "relative URL with empty baseURL returns error",
			rawURL:  "/docs/guide.pdf",
			baseURL: "",
			wantErr: true,
		},
		{
			name:    "disallow javascript pseudo-protocol",
			rawURL:  "javascript:alert(1)",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow file URI scheme",
			rawURL:  "file:///C:/Windows/System32/cmd.exe",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow data URI scheme",
			rawURL:  "data:text/html,<script>alert(1)</script>",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow ftp scheme",
			rawURL:  "ftp://ftp.example.com/doc.pdf",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			parsed, err := validateDocumentURL(tt.rawURL, tt.baseURL)
			if (err != nil) != tt.wantErr {
				t.Fatalf("validateDocumentURL(%q, %q) error = %v, wantErr %v", tt.rawURL, tt.baseURL, err, tt.wantErr)
			}
			if !tt.wantErr && parsed.String() != tt.wantURL {
				t.Errorf("validateDocumentURL(%q, %q) = %q, want %q", tt.rawURL, tt.baseURL, parsed.String(), tt.wantURL)
			}
		})
	}
}

func TestDocumentPDFMiddlewareServesUpstreamPDF(t *testing.T) {
	api := &documentAPI{stubAPI: stubAPI{status: 200, body: []byte("%PDF-1.4\n%fake\n")}}
	a := &App{Airspace: api}
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(http.StatusTeapot) })
	h := a.DocumentPDFMiddleware(next)

	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/documents/3/pdf", nil))
	if rec.Code != 200 || rec.Body.String() != "%PDF-1.4\n%fake\n" {
		t.Fatalf("unexpected response: %d %q", rec.Code, rec.Body.String())
	}
	if ct := rec.Header().Get("Content-Type"); ct != "application/pdf" {
		t.Fatalf("content type %q", ct)
	}
	if rec.Header().Get("X-Content-Type-Options") != "nosniff" || rec.Header().Get("Cache-Control") != "no-store" {
		t.Fatalf("missing hardening headers: %v", rec.Header())
	}
	if api.path != "/api/v2/acars/documents/3/pdf" {
		t.Fatalf("wrong upstream path: %s", api.path)
	}

	// Anything else on the asset server is passed through untouched.
	rec = httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/documents/3/pdf/../x", nil))
	rec2 := httptest.NewRecorder()
	h.ServeHTTP(rec2, httptest.NewRequest(http.MethodGet, "/index.html", nil))
	if rec2.Code != http.StatusTeapot {
		t.Fatalf("non-matching path must reach the asset handler, got %d", rec2.Code)
	}
	rec = httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodPost, "/documents/3/pdf", nil))
	if rec.Code != http.StatusMethodNotAllowed {
		t.Fatalf("POST must be refused, got %d", rec.Code)
	}
}

func TestDocumentPDFMiddlewareMapsStatusesAndRejectsNonPDF(t *testing.T) {
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { t.Fatal("must not fall through") })
	for status, want := range map[int]int{403: 403, 404: 404, 429: 429} {
		a := &App{Airspace: &documentAPI{stubAPI: stubAPI{status: status, body: []byte("{}")}}}
		rec := httptest.NewRecorder()
		a.DocumentPDFMiddleware(next).ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/documents/3/pdf", nil))
		if rec.Code != want {
			t.Fatalf("upstream %d: got %d", status, rec.Code)
		}
	}
	// An HTML login page must never be served as application/pdf.
	a := &App{Airspace: &documentAPI{stubAPI: stubAPI{status: 200, body: []byte("<html>login</html>")}}}
	rec := httptest.NewRecorder()
	a.DocumentPDFMiddleware(next).ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/documents/3/pdf", nil))
	if rec.Code != http.StatusBadGateway || rec.Header().Get("Content-Type") == "application/pdf" {
		t.Fatalf("non-PDF body served: %d %v", rec.Code, rec.Header())
	}
}

// The route has no auth of its own; it trusts the in-process asset server.
// A request that declares it came from somewhere other than the app's own
// page (a browser tab, another site) is refused, and one from a webview that
// sends no such header is served.
func TestDocumentPDFMiddlewareRefusesRequestsNotFromTheAppPage(t *testing.T) {
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { t.Fatal("must not fall through") })
	for _, site := range []string{"none", "cross-site", "same-site"} {
		api := &documentAPI{stubAPI: stubAPI{status: 200, body: []byte("%PDF-1.4\n")}}
		a := &App{Airspace: api}
		req := httptest.NewRequest(http.MethodGet, "/documents/3/pdf", nil)
		req.Header.Set("Sec-Fetch-Site", site)
		rec := httptest.NewRecorder()
		a.DocumentPDFMiddleware(next).ServeHTTP(rec, req)
		if rec.Code != http.StatusForbidden {
			t.Fatalf("Sec-Fetch-Site %q: got %d, want 403", site, rec.Code)
		}
		if api.calls != 0 {
			t.Fatalf("Sec-Fetch-Site %q: upstream was fetched", site)
		}
	}
	for _, site := range []string{"", "same-origin"} {
		a := &App{Airspace: &documentAPI{stubAPI: stubAPI{status: 200, body: []byte("%PDF-1.4\n")}}}
		req := httptest.NewRequest(http.MethodGet, "/documents/3/pdf", nil)
		if site != "" {
			req.Header.Set("Sec-Fetch-Site", site)
		}
		rec := httptest.NewRecorder()
		a.DocumentPDFMiddleware(next).ServeHTTP(rec, req)
		if rec.Code != http.StatusOK {
			t.Fatalf("Sec-Fetch-Site %q: got %d, want 200", site, rec.Code)
		}
	}
}
