package app

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/url"
	"strconv"
	"strings"

	"airspace-acars/internal/domain"
)

const documentsPath = "/api/v1/documents"

// documentRequest handles authenticated requests to tenant document endpoints.
func (a *App) documentRequest(path string) ([]byte, string, error) {
	if a.GetSettings().LocalMode {
		return nil, "localMode", nil
	}
	if a.Airspace.Token() == "" || a.Airspace.BaseURL() == "" {
		return nil, "noSession", nil
	}
	body, status, err := a.Airspace.DoRequest("GET", path, nil)
	if err != nil {
		return nil, "", err
	}
	slog.Info("documentRequest", "path", path, "status", status)
	switch status {
	case 401, 403:
		return nil, "accessDenied", nil
	case 404, 405:
		return nil, "unavailable", nil
	case 429:
		return nil, "rateLimited", nil
	}
	if err := domain.NewStatusError("GET", path, status, body); err != nil {
		return nil, "", err
	}
	return body, "ok", nil
}

type documentWire struct {
	ID              json.RawMessage `json:"id"`
	Title           string          `json:"title"`
	Type            string          `json:"type"`
	ParentID        json.RawMessage `json:"parent_id"`
	Visibility      string          `json:"visibility"`
	IsAutoGenerated interface{}     `json:"is_auto_generated"`
	Source          string          `json:"source"`
	Content         string          `json:"content"`
	Body            string          `json:"body"`
	FileURL         string          `json:"file_url"`
	PDFURL          string          `json:"pdf_url"`
	URL             string          `json:"url"`
	DownloadURL     string          `json:"download_url"`
	SortOrder       int             `json:"sort_order"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func parseRawID(raw json.RawMessage) (string, error) {
	if len(raw) == 0 || string(raw) == "null" {
		return "", nil
	}
	var str string
	if err := json.Unmarshal(raw, &str); err == nil {
		return str, nil
	}
	var num json.Number
	if err := json.Unmarshal(raw, &num); err == nil {
		return num.String(), nil
	}
	return "", fmt.Errorf("invalid id format")
}

func parseBoolLike(v interface{}) bool {
	switch val := v.(type) {
	case bool:
		return val
	case float64:
		return val != 0
	case int:
		return val != 0
	case string:
		return val == "1" || strings.EqualFold(val, "true")
	default:
		return false
	}
}

func (d documentWire) document() (domain.Document, error) {
	id, err := parseRawID(d.ID)
	if err != nil || id == "" {
		return domain.Document{}, fmt.Errorf("missing or invalid document id")
	}

	parentID, _ := parseRawID(d.ParentID)

	content := d.Content
	if content == "" {
		content = d.Body
	}

	fileURL := d.FileURL
	if fileURL == "" {
		fileURL = d.PDFURL
	}
	if fileURL == "" {
		fileURL = d.DownloadURL
	}
	if fileURL == "" {
		fileURL = d.URL
	}

	docType := strings.ToLower(strings.TrimSpace(d.Type))
	if docType == "" {
		if fileURL != "" {
			docType = "pdf"
		} else {
			docType = "html"
		}
	}

	return domain.Document{
		ID:              id,
		Title:           d.Title,
		Type:            docType,
		ParentID:        parentID,
		Visibility:      d.Visibility,
		IsAutoGenerated: parseBoolLike(d.IsAutoGenerated),
		Source:          d.Source,
		Content:         content,
		FileURL:         fileURL,
		SortOrder:       d.SortOrder,
		CreatedAt:       d.CreatedAt,
		UpdatedAt:       d.UpdatedAt,
	}, nil
}

// GetDocuments lists documents from the airline library with optional parent ID and search query.
func (a *App) GetDocuments(page int, parentID string, search string) (*domain.DocumentPage, error) {
	if page < 1 {
		page = 1
	}
	query := url.Values{
		"page":     {strconv.Itoa(page)},
		"per_page": {"100"},
		"sort":     {"sort_order"},
		"sort_dir": {"asc"},
	}
	if parentID != "" {
		query.Set("filter[parent_id]", parentID)
	}
	if search != "" {
		query.Set("filter[title]", search)
	}

	candidates := []string{
		documentsPath + "?" + query.Encode(),
		"/api/v2/acars/documents?" + query.Encode(),
		"/api/v2/acars/documents",
	}

	var body []byte
	var status string
	var err error

	for _, path := range candidates {
		body, status, err = a.documentRequest(path)
		if err != nil {
			return nil, err
		}
		if status == "ok" {
			break
		}
		if status == "localMode" || status == "noSession" {
			break
		}
	}

	result := &domain.DocumentPage{
		Status:      status,
		Data:        []domain.Document{},
		CurrentPage: page,
		LastPage:    page,
	}
	if status != "ok" {
		return result, nil
	}

	var response struct {
		Data        *[]documentWire `json:"data"`
		CurrentPage int             `json:"current_page"`
		LastPage    int             `json:"last_page"`
		Meta        struct {
			CurrentPage int `json:"current_page"`
			LastPage    int `json:"last_page"`
		} `json:"meta"`
	}
	if err := json.Unmarshal(body, &response); err != nil || response.Data == nil {
		return nil, fmt.Errorf("invalid document list response")
	}

	for _, item := range *response.Data {
		doc, err := item.document()
		if err != nil {
			continue
		}
		result.Data = append(result.Data, doc)
	}

	if response.Meta.CurrentPage > 0 {
		result.CurrentPage = response.Meta.CurrentPage
	} else if response.CurrentPage > 0 {
		result.CurrentPage = response.CurrentPage
	}
	if response.Meta.LastPage > 0 {
		result.LastPage = response.Meta.LastPage
	} else if response.LastPage > 0 {
		result.LastPage = response.LastPage
	}

	return result, nil
}

// GetDocument fetches detailed content for a single document.
func (a *App) GetDocument(id string) (*domain.DocumentDetail, error) {
	if id == "" || strings.ContainsAny(id, "/\\?#%") || id == "." || id == ".." {
		return nil, fmt.Errorf("invalid document id")
	}

	candidates := []string{
		documentsPath + "/" + url.PathEscape(id),
		"/api/v2/acars/documents/" + url.PathEscape(id),
	}

	var body []byte
	var status string
	var err error

	for _, path := range candidates {
		body, status, err = a.documentRequest(path)
		if err != nil {
			return nil, err
		}
		if status == "ok" {
			break
		}
		if status == "localMode" || status == "noSession" {
			break
		}
	}

	result := &domain.DocumentDetail{Status: status}
	if status != "ok" {
		return result, nil
	}

	var envelope struct {
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, fmt.Errorf("invalid document detail response")
	}
	if len(envelope.Data) > 0 {
		body = envelope.Data
	}

	var wire documentWire
	if err := json.Unmarshal(body, &wire); err != nil {
		return nil, fmt.Errorf("invalid document detail response")
	}
	doc, err := wire.document()
	if err != nil {
		return nil, err
	}
	result.Data = &doc
	return result, nil
}
