package app

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"strings"

	"airspace-acars/internal/domain"

	"github.com/pkg/browser"
)

const documentsPath = "/api/v2/acars/documents"

type documentWire struct {
	ID              json.RawMessage `json:"id"`
	Title           string          `json:"title"`
	Type            string          `json:"type"`
	ParentID        json.RawMessage `json:"parent_id"`
	Visibility      string          `json:"visibility"`
	IsAutoGenerated interface{}     `json:"is_auto_generated"`
	Source          string          `json:"source"`
	SourceType      string          `json:"source_type"`
	Content         string          `json:"content"`
	Body            string          `json:"body"`
	FileURL         string          `json:"file_url"`
	PDFURL          string          `json:"pdf_url"`
	URL             string          `json:"url"`
	DownloadURL     string          `json:"download_url"`
	SortOrder       int             `json:"sort_order"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func parseBoolLike(v interface{}) bool {
	switch val := v.(type) {
	case bool:
		return val
	case float64:
		return val != 0
	case int:
		return val != 0
	case string:
		return val == "1" || strings.EqualFold(val, "true")
	default:
		return false
	}
}

func (d documentWire) document() (domain.Document, error) {
	id, err := parseRawID(d.ID)
	if err != nil || id == "" {
		return domain.Document{}, fmt.Errorf("missing or invalid document id")
	}

	parentID, _ := parseRawID(d.ParentID)

	content := d.Content
	if content == "" {
		content = d.Body
	}

	fileURL := d.FileURL
	if fileURL == "" {
		fileURL = d.PDFURL
	}
	if fileURL == "" {
		fileURL = d.DownloadURL
	}
	if fileURL == "" {
		fileURL = d.URL
	}

	docType := strings.ToLower(strings.TrimSpace(d.Type))
	if docType == "" {
		if fileURL != "" {
			docType = "pdf"
		} else {
			docType = "html"
		}
	}

	return domain.Document{
		ID:              id,
		Title:           d.Title,
		Type:            docType,
		ParentID:        parentID,
		Visibility:      d.Visibility,
		IsAutoGenerated: parseBoolLike(d.IsAutoGenerated),
		Source:          d.Source,
		SourceType:      d.SourceType,
		Content:         content,
		FileURL:         fileURL,
		SortOrder:       d.SortOrder,
		CreatedAt:       d.CreatedAt,
		UpdatedAt:       d.UpdatedAt,
	}, nil
}

// GetDocuments lists documents from the airline library with optional parent ID and search query.
func (a *App) GetDocuments(page int, parentID string, search string) (*domain.DocumentPage, error) {
	if page < 1 {
		page = 1
	}
	query := url.Values{
		"page":     {strconv.Itoa(page)},
		"per_page": {"100"},
		"sort":     {"sort_order"},
		"sort_dir": {"asc"},
	}
	if parentID != "" {
		query.Set("filter[parent_id]", parentID)
	}
	if search != "" {
		query.Set("filter[title]", search)
	}

	candidates := []string{
		documentsPath + "?" + query.Encode(),
	}

	body, status, err := executeCandidates(candidates, a.executeRequest)
	if err != nil {
		return nil, err
	}

	result := &domain.DocumentPage{
		Status:      status,
		Data:        []domain.Document{},
		CurrentPage: page,
		LastPage:    page,
	}
	if status != "ok" {
		return result, nil
	}

	var response struct {
		Data        *[]documentWire `json:"data"`
		CurrentPage int             `json:"current_page"`
		LastPage    int             `json:"last_page"`
		Meta        struct {
			CurrentPage int `json:"current_page"`
			LastPage    int `json:"last_page"`
		} `json:"meta"`
	}
	if err := json.Unmarshal(body, &response); err != nil || response.Data == nil {
		return nil, fmt.Errorf("invalid document list response")
	}

	for _, item := range *response.Data {
		doc, err := item.document()
		if err != nil {
			continue
		}
		result.Data = append(result.Data, doc)
	}

	if response.Meta.CurrentPage > 0 {
		result.CurrentPage = response.Meta.CurrentPage
	} else if response.CurrentPage > 0 {
		result.CurrentPage = response.CurrentPage
	}
	if response.Meta.LastPage > 0 {
		result.LastPage = response.Meta.LastPage
	} else if response.LastPage > 0 {
		result.LastPage = response.LastPage
	}

	return result, nil
}

// GetDocument fetches detailed content for a single document.
func (a *App) GetDocument(id string) (*domain.DocumentDetail, error) {
	if id == "" || strings.ContainsAny(id, "/\\?#%") || id == "." || id == ".." {
		return nil, fmt.Errorf("invalid document id")
	}

	candidates := []string{
		documentsPath + "/" + url.PathEscape(id),
	}

	body, status, err := executeCandidates(candidates, a.executeRequest)
	if err != nil {
		return nil, err
	}

	result := &domain.DocumentDetail{Status: status}
	if status != "ok" {
		return result, nil
	}

	var envelope struct {
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, fmt.Errorf("invalid document detail response")
	}
	if len(envelope.Data) > 0 {
		body = envelope.Data
	}

	var wire documentWire
	if err := json.Unmarshal(body, &wire); err != nil {
		return nil, fmt.Errorf("invalid document detail response")
	}
	doc, err := wire.document()
	if err != nil {
		return nil, err
	}
	result.Data = &doc
	return result, nil
}

// validateDocumentURL parses, resolves relative references against baseURL, and
// ensures the scheme is strictly http or https.
func validateDocumentURL(rawURL string, baseURL string) (*url.URL, error) {
	rawURL = strings.TrimSpace(rawURL)
	if rawURL == "" {
		return nil, fmt.Errorf("empty URL")
	}

	parsed, err := url.Parse(rawURL)
	if err != nil {
		return nil, fmt.Errorf("invalid URL: %w", err)
	}

	// Resolve relative or scheme-less URL against tenant base URL
	if !parsed.IsAbs() {
		if baseURL == "" {
			return nil, fmt.Errorf("cannot resolve relative URL: tenant base URL is not set")
		}
		baseParsed, err := url.Parse(baseURL)
		if err != nil {
			return nil, fmt.Errorf("invalid tenant base URL: %w", err)
		}
		parsed = baseParsed.ResolveReference(parsed)
	}

	scheme := strings.ToLower(parsed.Scheme)
	if scheme != "http" && scheme != "https" {
		return nil, fmt.Errorf("unsupported URL scheme: %s", scheme)
	}

	return parsed, nil
}

// OpenDocumentURL validates a server-provided document URL and opens it in the
// default system browser. It resolves relative paths against the active tenant
// base URL and strictly enforces http/https schemes.
func (a *App) OpenDocumentURL(rawURL string) error {
	baseURL := ""
	if a.Airspace != nil {
		baseURL = a.Airspace.BaseURL()
	}
	parsed, err := validateDocumentURL(rawURL, baseURL)
	if err != nil {
		return err
	}

	return browser.OpenURL(parsed.String())
}
