package app

import (
	"net/url"
	"testing"
)

type documentAPI struct {
	stubAPI
	path string
}

func (*documentAPI) Token() string { return "pilot-token" }
func (s *documentAPI) DoRequest(method, path string, body interface{}) ([]byte, int, error) {
	s.path = path
	return s.stubAPI.DoRequest(method, path, body)
}

func TestDocumentListPaginationAndQuery(t *testing.T) {
	api := &documentAPI{stubAPI: stubAPI{
		status: 200,
		body:   []byte(`{"data":[{"id":101,"title":"B737 SOP","type":"html","content":"<p>Standard Operating Procedures</p>","is_auto_generated":0,"parent_id":null}],"meta":{"current_page":1,"last_page":2}}`),
	}}
	a := &App{Airspace: api}
	result, err := a.GetDocuments(1, "folder_5", "SOP")
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "ok" || len(result.Data) != 1 || result.Data[0].ID != "101" || result.Data[0].Title != "B737 SOP" {
		t.Fatalf("unexpected response: %+v", result)
	}
	u, _ := url.Parse(api.path)
	q := u.Query()
	if u.Path != documentsPath || q.Get("filter[parent_id]") != "folder_5" || q.Get("filter[title]") != "SOP" {
		t.Fatalf("wrong request: %s", api.path)
	}
}

func TestDocumentUnavailableStatuses(t *testing.T) {
	for status, want := range map[int]string{401: "accessDenied", 403: "accessDenied", 404: "unavailable", 405: "unavailable", 429: "rateLimited"} {
		api := &documentAPI{stubAPI: stubAPI{status: status, body: []byte("error")}}
		a := &App{Airspace: api}
		result, err := a.GetDocuments(1, "", "")
		if err != nil || result.Status != want {
			t.Fatalf("status %d: got status %q, want %q (err: %v)", status, result.Status, want, err)
		}
	}
}

func TestDocumentLocalModeAndNoSession(t *testing.T) {
	api := &documentAPI{}
	a := &App{Airspace: api}
	a.settings.LocalMode = true
	result, err := a.GetDocuments(1, "", "")
	if err != nil || result.Status != "localMode" || api.calls != 0 {
		t.Fatalf("unexpected local request: %+v %v", result, err)
	}

	noSession := &stubAPI{}
	a = &App{Airspace: noSession}
	result, err = a.GetDocuments(1, "", "")
	if err != nil || result.Status != "noSession" || noSession.calls != 0 {
		t.Fatalf("unexpected anonymous request: %+v %v", result, err)
	}
}

func TestDocumentDetailAndSecurity(t *testing.T) {
	api := &documentAPI{stubAPI: stubAPI{status: 200}}
	a := &App{Airspace: api}
	api.body = []byte(`{"data":{"id":"202","title":"Airport Briefing SBGR","type":"auto_generated","content":"<p>Obstacles and terrain caution</p>","is_auto_generated":1}}`)
	detail, err := a.GetDocument("202")
	if err != nil || detail.Data == nil || detail.Data.ID != "202" || !detail.Data.IsAutoGenerated {
		t.Fatalf("unexpected detail: %+v %v", detail, err)
	}

	for _, unsafeID := range []string{"", "../etc/passwd", "https://evil.com", "folder/file", "%2e%2e"} {
		if _, err := a.GetDocument(unsafeID); err == nil {
			t.Fatalf("accepted unsafe document id: %q", unsafeID)
		}
	}
}

func TestValidateDocumentURL(t *testing.T) {
	tests := []struct {
		name    string
		rawURL  string
		baseURL string
		wantURL string
		wantErr bool
	}{
		{
			name:    "valid https URL",
			rawURL:  "https://airspace.ferrlab.com/docs/sop.pdf",
			baseURL: "https://airspace.ferrlab.com",
			wantURL: "https://airspace.ferrlab.com/docs/sop.pdf",
		},
		{
			name:    "valid http URL",
			rawURL:  "http://example.com/briefing.html",
			baseURL: "https://airspace.ferrlab.com",
			wantURL: "http://example.com/briefing.html",
		},
		{
			name:    "valid relative URL resolved against base URL",
			rawURL:  "/storage/documents/manual.pdf",
			baseURL: "https://airline.example.com",
			wantURL: "https://airline.example.com/storage/documents/manual.pdf",
		},
		{
			name:    "empty URL returns error",
			rawURL:  "",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "whitespace only returns error",
			rawURL:  "   ",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "relative URL with empty baseURL returns error",
			rawURL:  "/docs/guide.pdf",
			baseURL: "",
			wantErr: true,
		},
		{
			name:    "disallow javascript pseudo-protocol",
			rawURL:  "javascript:alert(1)",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow file URI scheme",
			rawURL:  "file:///C:/Windows/System32/cmd.exe",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow data URI scheme",
			rawURL:  "data:text/html,<script>alert(1)</script>",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
		{
			name:    "disallow ftp scheme",
			rawURL:  "ftp://ftp.example.com/doc.pdf",
			baseURL: "https://airline.example.com",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			parsed, err := validateDocumentURL(tt.rawURL, tt.baseURL)
			if (err != nil) != tt.wantErr {
				t.Fatalf("validateDocumentURL(%q, %q) error = %v, wantErr %v", tt.rawURL, tt.baseURL, err, tt.wantErr)
			}
			if !tt.wantErr && parsed.String() != tt.wantURL {
				t.Errorf("validateDocumentURL(%q, %q) = %q, want %q", tt.rawURL, tt.baseURL, parsed.String(), tt.wantURL)
			}
		})
	}
}

