package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// gen turns the HubHop database into draft aircraft profiles.
//
// Only the variables it can read with confidence become bindings: the preset
// has to be readable, its code has to be a single variable with at most a
// simple arithmetic or comparison tail, and its label has to match one of the
// rules below. Everything else is left alone — the adapter's own reading is
// already right for most aircraft, and a wrong override is worse than none.
func gen(args []string) {
	fset := flag.NewFlagSet("gen", flag.ExitOnError)
	sim := fset.String("sim", "msfs", "simulator database: msfs or xplane")
	out := fset.String("out", "internal/profiles/builtin", "directory to write profiles into")
	minPoints := fset.Int("min-points", 1, "skip aircraft with fewer mapped data points than this")
	dry := fset.Bool("dry-run", false, "print what would be written without writing it")
	fset.Parse(flagsFirst(args))

	presets, err := fetch(*sim)
	exitOn(err)

	simulator := "simconnect"
	if *sim != "msfs" {
		simulator = "xplane"
	}

	// Existing profiles are hand-written and win: a generated draft never
	// overwrites one, and never competes with one for the same aircraft.
	existing := map[string]bool{}
	if entries, err := os.ReadDir(*out); err == nil {
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".json") {
				continue
			}
			body, err := os.ReadFile(filepath.Join(*out, e.Name()))
			if err != nil {
				continue
			}
			var doc struct {
				ID        string `json:"id"`
				Generated bool   `json:"x-generated"`
			}
			if json.Unmarshal(body, &doc) == nil && doc.ID != "" && !doc.Generated {
				// Only profiles a person owns are protected. A draft still
				// carrying the x-generated marker is refreshed in place;
				// deleting the marker adopts it and freezes it.
				existing[doc.ID] = true
			}
		}
	}

	groups := map[string][]preset{}
	for _, p := range presets {
		if !strings.Contains(p.PresetType, "Output") {
			continue
		}
		if skipVendor(p.Vendor) || strings.EqualFold(p.Aircraft, "Generic") {
			continue
		}
		key := p.Vendor + "\x00" + p.Aircraft
		groups[key] = append(groups[key], p)
	}

	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	written, skipped := 0, 0
	for _, key := range keys {
		parts := strings.SplitN(key, "\x00", 2)
		vendor, aircraft := parts[0], parts[1]

		id := profileID(vendor, aircraft)
		if existing[id] || handWritten.MatchString(vendor+" "+aircraft) {
			skipped++
			continue
		}

		mash := buildMash(groups[key], simulator)
		if len(mash) < *minPoints {
			continue
		}

		sel, ok := selector(vendor, aircraft, simulator)
		if !ok {
			continue
		}
		doc := map[string]any{
			"id":          id,
			"name":        strings.TrimSpace(vendor + " " + cleanModel(aircraft)),
			"description": fmt.Sprintf("%s. Reads the data points below from the aircraft's own variables instead of the stock ones.", strings.TrimSpace(vendor+" "+cleanModel(aircraft))),
			"notes": "Generated by `go run ./cmd/hubhop gen` from the MobiFlight HubHop community " +
				"database. The selector and the bindings have not been confirmed in the simulator: " +
				"treat this as a starting point, and correct it in place once flown. Every binding " +
				"falls back to the stock variable, so an unread aircraft variable costs nothing.",
			"x-generated": true,
			"priority":    50,
			"match":       sel,
			"mash":        mash,
		}

		path := filepath.Join(*out, id+".json")
		if *dry {
			fmt.Printf("%-34s %-44s %d point(s)\n", id, vendor+" "+aircraft, len(mash))
			continue
		}
		body, err := json.MarshalIndent(doc, "", "  ")
		exitOn(err)
		exitOn(os.WriteFile(path, append(body, '\n'), 0o644))
		written++
		fmt.Printf("%-34s %-44s %d point(s)\n", id, vendor+" "+aircraft, len(mash))
	}
	fmt.Fprintf(os.Stderr, "\n%d profile(s) written, %d aircraft already covered by a hand-written profile\n", written, skipped)
}

// skipVendor drops the entries that are not a specific add-on aircraft.
func skipVendor(vendor string) bool {
	switch strings.ToLower(strings.TrimSpace(vendor)) {
	case "", "microsoft", "asobo", "unknown", "generic":
		return true
	}
	return false
}

// --- code parsing -----------------------------------------------------------

// simpleCode is a HubHop code reduced to one variable plus a transform this
// project can express. Anything with branching, several variables or an
// operator outside the set below is rejected rather than guessed at.
type simpleCode struct {
	kind  string // lvar, simvar or dataref
	name  string
	unit  string
	steps []map[string]any
}

var (
	varRe  = regexp.MustCompile(`^\(\s*([LAK]):([^,)]+?)\s*(?:,\s*([^)]*?)\s*)?\)`)
	drefRe = regexp.MustCompile(`^([A-Za-z0-9_]+(?:/[A-Za-z0-9_\-.]+)+(?:\[\d+\])?)$`)
	numRe  = regexp.MustCompile(`^-?\d+(?:\.\d+)?$`)
)

var opNames = map[string]string{
	">": "gt", "<": "lt", ">=": "gte", "<=": "lte", "==": "eq", "!=": "ne",
	"*": "scale", "/": "divide", "+": "offset",
}

func parseCode(code, simulator string) (simpleCode, bool) {
	code = strings.TrimSpace(code)

	if simulator == "xplane" {
		if drefRe.MatchString(code) {
			return simpleCode{kind: "dataref", name: code}, true
		}
		return simpleCode{}, false
	}

	m := varRe.FindStringSubmatch(code)
	if m == nil {
		return simpleCode{}, false
	}
	kind := map[string]string{"L": "lvar", "A": "simvar"}[m[1]]
	if kind == "" {
		return simpleCode{}, false // K: is an event, not readable
	}

	sc := simpleCode{kind: kind, name: strings.TrimSpace(m[2])}
	if kind == "simvar" {
		sc.unit = strings.TrimSpace(m[3])
	}
	if sc.name == "" || strings.ContainsAny(sc.name, "()>< ") && kind == "lvar" {
		return simpleCode{}, false
	}

	// The tail must be a flat sequence of "<number> <operator>" pairs or "!".
	rest := strings.Fields(strings.TrimSpace(code[len(m[0]):]))
	for i := 0; i < len(rest); i++ {
		if rest[i] == "!" {
			sc.steps = append(sc.steps, map[string]any{"op": "not"})
			continue
		}
		if !numRe.MatchString(rest[i]) || i+1 >= len(rest) {
			return simpleCode{}, false
		}
		value, err := strconv.ParseFloat(rest[i], 64)
		if err != nil {
			return simpleCode{}, false
		}
		op, ok := opNames[rest[i+1]]
		if !ok {
			return simpleCode{}, false
		}
		if op == "divide" && value == 0 {
			return simpleCode{}, false
		}
		sc.steps = append(sc.steps, map[string]any{"op": op, "value": value})
		i++
	}
	return sc, true
}

// aircraftSpecific reports whether the code reads something the add-on adds,
// rather than a variable the adapter already collects by default.
func (s simpleCode) aircraftSpecific(simulator string) bool {
	if simulator == "xplane" {
		return !strings.HasPrefix(s.name, "sim/")
	}
	return s.kind == "lvar"
}

func (s simpleCode) yieldsBool() bool {
	for _, st := range s.steps {
		switch st["op"] {
		case "gt", "lt", "gte", "lte", "eq", "ne", "not":
			return true
		}
	}
	return false
}

func (s simpleCode) binding(simulator string, extra []map[string]any) map[string]any {
	src := map[string]any{"kind": s.kind, "name": s.name}
	if s.unit != "" {
		src["unit"] = s.unit
	}
	b := map[string]any{"sim": simulator, "source": src}
	if steps := append(append([]map[string]any{}, s.steps...), extra...); len(steps) > 0 {
		b["transform"] = steps
	}
	return b
}

// --- data point rules -------------------------------------------------------

// rule maps HubHop labels onto one of the ACARS data points. Matching is
// deliberately narrow: the label has to name the concept AND, for the boolean
// points, look like an indication rather than a command.
type rule struct {
	point string
	// want and not are matched against the preset's label and description.
	want *regexp.Regexp
	not  *regexp.Regexp
	// name is matched against the variable's own name. A label can describe
	// anything; requiring the variable to be named for the concept as well is
	// what stops an "AP ALT light" from being read as "autopilot engaged".
	name     *regexp.Regexp
	reduce   string // or / and / "" for first-usable-wins
	numeric  bool   // a value rather than a lamp: take the single best candidate
	fallback map[string]simpleCode
}

func re(pattern string) *regexp.Regexp { return regexp.MustCompile("(?i)" + pattern) }

// lampNameRe matches a variable named for an indication rather than a value.
// Underscores and slashes are the separators these names actually use, which
// a word boundary does not see.
var lampNameRe = re(`(^|[_/])(ann|annun|led|light|lt|lamp|button|btn|switch|sw|dashed|` +
	`managed|dot|source|digits|status|mode|arm|armed)([_/0-9]|$)`)

func sv(name, unit string) simpleCode { return simpleCode{kind: "simvar", name: name, unit: unit} }
func dref(name string) simpleCode     { return simpleCode{kind: "dataref", name: name} }

// indication is the shape of a label that reports a state rather than sets one.
const indication = `(ind|indicator|annunciator|annu|led|light|lt\b|lamp|active|engaged?|status|state|on\b|mode)`

// otherModes are the autopilot modes that are not "engaged". A variable named
// for one of them reports that mode, never the master switch.
const otherModes = `alt|hdg|heading|nav|vnav|lnav|vs\b|vvi|ias|mach|spd|speed|app|loc|glide|` +
	`backcourse|attitude|level|trk|fpa|go.?around|wing|yaw|turb|bank|volt|fail|preselect|beam`

// lampWords mark a preset that reports a lamp or a button rather than a value.
const lampWords = `\b(led|lamp|light|button|annunciator|annu|switch|knob|dashed|dash|managed|` +
	`dot|arm(ed)?|status|source|page|index|bright)\b`

var rules = []rule{
	{
		point: "autopilot.master",
		want: re(`\b(cmd ?[ab]|ap ?[12]|autopilot ?[12]?|a/?p|afs)\b.*` + indication +
			`|` + indication + `.*\b(cmd ?[ab]|ap ?[12]|autopilot)\b`),
		not:    re(`disengage|disconnect|disc\b|warn|caution|test|reset|trim|servo|bright|` + otherModes),
		name:   re(`^(?:.*[_/])?(?:(?:mcp_)?(?:cmd|ap|a_?p|autopilot|afs)[_ ]?[ab12]?)(?:[_ ](?:on|active|engaged?|status|state|comm|ann|light|lt|led))?$|autopilot[_ ]?(1|2)?[_ ]?active|ap[12][_ ]?on`),
		reduce: "or",
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT MASTER", "Bool"),
			"xplane":     dref("sim/cockpit/autopilot/autopilot_mode"),
		},
	},
	{
		point:  "autopilot.navLock",
		want:   re(`\b(lnav|nav mode|vor ?loc|vorloc)\b`),
		not:    re(`deviation|scale|pointer|needle|warn|fail|glide|freq|standby|swap|source|bright`),
		name:   re(`lnav|vor_?loc|vorloc|nav_?(mode|status|ann|on|active)`),
		reduce: "or",
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT NAV1 LOCK", "Bool"),
			"xplane":     dref("sim/cockpit2/autopilot/nav_status"),
		},
	},
	{
		point:  "autopilot.approachHold",
		want:   re(`\b(appr?|approach)\b`),
		not:    re(`speed|flap|idle|minimum|warn|fail|bright|category|cat ?(1|2|3|i)|armed`),
		name:   re(`appr?(oach)?(_|$|[_ ]?(on|light|lt|led|ann|active|mode|button))`),
		reduce: "or",
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT APPROACH HOLD", "Bool"),
			"xplane":     dref("sim/cockpit2/autopilot/approach_status"),
		},
	},
	{
		point:   "autopilot.heading",
		want:    re(`\b(hdg|heading)\b.*\b(display|window|value|selected|sel|setting|indication)\b`),
		not:     re(`true|magnetic heading|bug scale|trk|track|` + lampWords),
		name:    re(`(hdg|heading)`),
		numeric: true,
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT HEADING LOCK DIR", "degrees"),
			"xplane":     dref("sim/cockpit/autopilot/heading_mag"),
		},
	},
	{
		point:   "autopilot.altitude",
		want:    re(`\b(alt|altitude)\b.*\b(display|window|value|selected|sel|setting|indication)\b`),
		not:     re(`cabin|pressur|radio|decision|elevation|landing|hold|mode|` + lampWords),
		name:    re(`alt`),
		numeric: true,
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT ALTITUDE LOCK VAR", "feet"),
			"xplane":     dref("sim/cockpit/autopilot/altitude"),
		},
	},
	{
		point:   "autopilot.speed",
		want:    re(`\b(spd|speed|ias|mach)\b.*\b(display|window|value|selected|sel|setting|indication|target)\b`),
		not:     re(`ground|vertical|wind|v1|vr\b|v2|flap|tape|trend|brake|` + lampWords),
		name:    re(`(spd|speed|ias|mach)`),
		numeric: true,
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT AIRSPEED HOLD VAR", "knots"),
			"xplane":     dref("sim/cockpit/autopilot/airspeed"),
		},
	},
	{
		point:   "autopilot.vs",
		want:    re(`\b(v/?s|vertical speed|vvi)\b.*\b(display|window|value|selected|sel|setting|indication)\b`),
		not:     re(`fpa|` + lampWords),
		name:    re(`(vs|vvi|vert)`),
		numeric: true,
		fallback: map[string]simpleCode{
			"simconnect": sv("AUTOPILOT VERTICAL HOLD VAR", "feet/minute"),
			"xplane":     dref("sim/cockpit/autopilot/vertical_velocity"),
		},
	},
	{
		point:  "apu.switchOn",
		want:   re(`apu.*master.*(sw|switch|button|on)\b`),
		not:    re(`fault|fire|test|reset|gen|bleed|avail|start|egt|rpm|n1|n2|off|door|flap|page|ecam`),
		name:   re(`apu.*(master|mstr)`),
		reduce: "or",
		fallback: map[string]simpleCode{
			"simconnect": sv("APU SWITCH", "Bool"),
		},
	},
	{
		point:   "apu.rpmPercent",
		want:    re(`apu.*\b(n1|rpm|speed|n%)\b`),
		not:     re(`n2|egt|fault|fire|max|limit|` + lampWords),
		name:    re(`apu.*(n1|rpm|speed)`),
		numeric: true,
		fallback: map[string]simpleCode{
			"simconnect": sv("APU PCT RPM", "Percent"),
		},
	},
	{
		point:  "controls.gearDown",
		want:   re(`gear.*\b(down|safe|locked)\b`),
		not:    re(`unsafe|transit|unlk|unlock|warn|horn|door|handle|lever|\bup\b|not locked|disagree|tilt|brake`),
		name:   re(`gear`),
		reduce: "and",
		fallback: map[string]simpleCode{
			"simconnect": sv("GEAR HANDLE POSITION", "Bool"),
			"xplane":     dref("sim/cockpit/switches/gear_handle_status"),
		},
	},
}

// buildMash turns one aircraft's presets into the mash section of a profile.
func buildMash(presets []preset, simulator string) map[string]any {
	mash := map[string]any{}

	for _, r := range rules {
		var candidates []simpleCode
		seen := map[string]bool{}

		for _, p := range presets {
			text := p.Label + " " + p.Description
			if !r.want.MatchString(text) || (r.not != nil && r.not.MatchString(text)) {
				continue
			}
			sc, ok := parseCode(p.Code, simulator)
			if !ok || seen[sc.name] {
				continue
			}
			// The variable has to be named for the concept, not merely
			// mentioned by a label that also names it.
			if r.name != nil && !r.name.MatchString(sc.name) {
				continue
			}
			// A generated profile only earns its place by binding something
			// the adapter does not already read. A stock simulation variable
			// or a stock X-Plane dataref is either a no-op or a mistake.
			if !sc.aircraftSpecific(simulator) {
				continue
			}
			// A value cannot come from a comparison, and a lamp is not a value —
			// "mcp_vs_dial_ann" reports the annunciator, not the selection.
			if r.numeric && (sc.yieldsBool() || lampNameRe.MatchString(sc.name)) {
				continue
			}
			seen[sc.name] = true
			candidates = append(candidates, sc)
		}
		if len(candidates) == 0 {
			continue
		}
		sort.Slice(candidates, func(i, j int) bool { return candidates[i].name < candidates[j].name })

		if r.numeric && len(candidates) > 1 {
			candidates = candidates[:1]
		}

		boolify := []map[string]any{{"op": "bool"}}
		var bindings []map[string]any
		for _, sc := range candidates {
			extra := []map[string]any(nil)
			if !r.numeric && !sc.yieldsBool() {
				extra = boolify
			}
			bindings = append(bindings, sc.binding(simulator, extra))
		}
		if fb, ok := r.fallback[simulator]; ok {
			extra := []map[string]any(nil)
			if !r.numeric {
				extra = boolify
			}
			bindings = append(bindings, fb.binding(simulator, extra))
		}

		if r.reduce != "" && len(bindings) > 1 {
			mash[r.point] = map[string]any{"reduce": r.reduce, "bindings": bindings}
		} else {
			mash[r.point] = bindings
		}
	}
	return mash
}

// --- naming and selectors ---------------------------------------------------

// handWritten matches the aircraft a hand-written profile already covers.
// Those profiles were checked against the aircraft's own files, so a generated
// draft must not compete with one.
var handWritten = re(`fenixsim|flight sim labs|fly by wire.*a320|pmdg.*(b737|b777)|` +
	`inibuilds.*(a350|a300|a310)|tfdi|aerosoft.*crj|ifly|just flight.*(bae|avro)|` +
	`leonardo|salty|zibo`)

// vendorPatterns maps a HubHop vendor onto the way its name actually appears
// in an aircraft title. An empty pattern means the vendor is not distinctive
// enough to put in a selector and the model has to carry it alone.
var vendorPatterns = map[string]string{
	"fly by wire":            `flybywire|fbw|a32nx`,
	"flight sim labs":        `fs\s*-?labs?`,
	"inibuilds":              `ini\s*-?builds?|inisim`,
	"just flight":            `just\s*-?flight`,
	"black square":           `black\s*-?square`,
	"a2a sim":                `a2a`,
	"hype performance group": `hype|hpg`,
	"flightsim studio (fss)": `fss|flightsim studio`,
	"dc designs":             `dc\s*-?designs`,
	"flight factor":          `flight\s*-?factor|ff`,
	"x-crafts":               `x\s*-?crafts`,
	"laminar research":       ``,
	"toliss":                 `toliss`,
	"ixeg":                   `ixeg`,
	"felis":                  `felis`,
}

var (
	parenRe    = regexp.MustCompile(`\s*\([^)]*\)`)
	suffixRe   = regexp.MustCompile(`(?i)\s*-\s*(sdk|dev|beta|wip)\b`)
	nonAlnumRe = regexp.MustCompile(`[^A-Za-z0-9]+`)
)

// cleanModel strips the bookkeeping HubHop carries in the aircraft name.
func cleanModel(aircraft string) string {
	return strings.TrimSpace(suffixRe.ReplaceAllString(parenRe.ReplaceAllString(aircraft, ""), ""))
}

// vendorIDs shorten the vendor half of a generated profile id.
var vendorIDs = map[string]string{
	"fly by wire":            "fbw",
	"flight sim labs":        "fslabs",
	"flightsim studio (fss)": "fss",
	"flight factor":          "flightfactor",
	"just flight":            "justflight",
	"black square":           "blacksquare",
	"hype performance group": "hpg",
	"dc designs":             "dcdesigns",
	"a2a sim":                "a2a",
	"headwind simulations":   "headwind",
	"miltech simulations":    "miltech",
	"x-crafts":               "xcrafts",
	"laminar research":       "laminar",
}

// profileID builds a stable, file-safe id from the vendor and the model.
func profileID(vendor, aircraft string) string {
	slug := func(s string) string {
		return strings.Trim(strings.ToLower(nonAlnumRe.ReplaceAllString(s, "-")), "-")
	}
	v, ok := vendorIDs[strings.ToLower(strings.TrimSpace(vendor))]
	if !ok {
		v = slug(vendor)
	}
	m := slug(cleanModel(aircraft))
	if m == "" {
		return v
	}
	return v + "-" + m
}

// tokenRe splits a model name into its letter and digit runs.
var (
	tokenRe    = regexp.MustCompile(`[A-Za-z]+|\d+`)
	wildcardRe = re(`x{2,}`)
)

// modelPattern turns a model name into a regular expression that tolerates the
// spacing and hyphens liveries vary on: "A340-600" and "A340 600" both match
// `a[\s-]*340`. It reports false for a family placeholder such as "E1XX",
// which names no aircraft a title would ever carry.
func modelPattern(model string) (string, bool) {
	if model == "" || wildcardRe.MatchString(model) {
		return "", false
	}
	tokens := tokenRe.FindAllString(strings.ToLower(model), -1)
	if len(tokens) == 0 {
		return "", false
	}

	// Prefer "<short letter prefix><number>", the way airframes are named.
	for i, tok := range tokens {
		if len(tok) < 2 || tok[0] < '0' || tok[0] > '9' {
			continue
		}
		if i > 0 && len(tokens[i-1]) <= 3 && tokens[i-1][0] >= 'a' {
			return regexp.QuoteMeta(tokens[i-1]) + `[\s-]*` + tok, true
		}
		return tok, true
	}

	// No model number: fall back to the words themselves ("Concorde", "Duke").
	words := make([]string, 0, len(tokens))
	for _, tok := range tokens {
		if len(tok) >= 3 {
			words = append(words, regexp.QuoteMeta(tok))
		}
	}
	if len(words) == 0 {
		return "", false
	}
	return strings.Join(words, `[\s-]*`), true
}

// selector builds the match expression: the simulator, the vendor as it shows
// up in a title where that is distinctive, and the model number with the
// spacing and hyphens liveries vary on. It reports false when the aircraft
// name carries nothing specific enough to match on.
func selector(vendor, aircraft, simulator string) (map[string]any, bool) {
	conds := []map[string]any{
		{"field": "simulator", "op": "equals", "value": simulator},
	}

	if pattern, ok := vendorPatterns[strings.ToLower(strings.TrimSpace(vendor))]; ok {
		if pattern != "" {
			conds = append(conds, map[string]any{"field": "aircraftName", "op": "matches", "value": pattern})
		}
	} else if v := strings.TrimSpace(vendor); v != "" {
		conds = append(conds, map[string]any{
			"field": "aircraftName", "op": "matches",
			"value": regexp.QuoteMeta(strings.ToLower(strings.Fields(v)[0])),
		})
	}

	pattern, ok := modelPattern(cleanModel(aircraft))
	if !ok {
		return nil, false
	}
	conds = append(conds, map[string]any{"field": "aircraftName", "op": "matches", "value": pattern})

	if len(conds) < 3 {
		return nil, false // the simulator plus one clause is too loose to ship
	}
	return map[string]any{"all": conds}, true
}
