package domain

// Document is the read-only documentation item shown to a pilot (manuals, SOPs, FDM profiles, Airport Briefings).
type Document struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Type            string `json:"type"` // "html", "pdf", "auto_generated", "folder"
	ParentID        string `json:"parent_id,omitempty"`
	Visibility      string `json:"visibility,omitempty"`
	IsAutoGenerated bool   `json:"is_auto_generated"`
	Source          string `json:"source,omitempty"`
	Content         string `json:"content,omitempty"`
	FileURL         string `json:"file_url,omitempty"`
	SortOrder       int    `json:"sort_order"`
	CreatedAt       string `json:"created_at,omitempty"`
	UpdatedAt       string `json:"updated_at,omitempty"`
}

// Status is a UI translation key suffix, never an upstream error body.
type DocumentPage struct {
	Status      string     `json:"status"`
	Data        []Document `json:"data"`
	CurrentPage int        `json:"current_page"`
	LastPage    int        `json:"last_page"`
}

type DocumentDetail struct {
	Status string    `json:"status"`
	Data   *Document `json:"data"`
}
